<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700italic,700');
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Merriweather:400,400i|Roboto:300,300i,400,400i,700,700i');
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$title = $this->pageTitle($site->title());
$logo = $this->themeSettingAssetUrl('logo');
if ($logo):
    $title = '<img src="' . $this->escapeHtml($logo) . '">';
endif;
$userBar = $this->partial('common/user-bar', ['site' => $site]);
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>

    <?php $sitetitle = strtolower($site->title());?>
    <?php $sitetitle = str_replace(' ', '-', $sitetitle);?>

    <?php echo $this->htmlElement('body')->setAttribute('class',$sitetitle);?>
        <?php echo $userBar; ?>
        <header>
            <nav>
              <div class="hero-top">
                <div class="intro">
                  <div class="title-box">
                    <a class="menu-btn" href="#">&#9776;</a>
                    <?php if ($this->themeSetting('logo')): ?>
                    <a href="<?php echo $site->url(); ?>" class="site-title"><img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" title="Logo"></a>
                    <?php else: ?>
                    <a href="<?php echo $site->url(); ?>" class="site-title"><span class="retopea">Retopea</span>

                    </a>
                    <a href="<?php echo $site->url(); ?>" class="site-sub-title">
                      <?php if($site->title() == "Start"):?>
                          Religious Toleration and Peace
                      <?php else: ?>
                          <?php echo $site->title(); ?>
                      <?php endif; ?>
                    </a>
                    <?php endif; ?>
                  </div>
                </div>
              </div>
            <?php
            echo $site->publicNav()->menu()->renderMenu(null, [
                'maxDepth' => $this->themeSetting('nav_depth') - 1
            ]);
            ?>

            <div id="search">
                <?php echo $this->partial('common/search-form'); ?>
            </div>
            </nav>
        </header>

        <div class="hero">
          <div class="intro">
            <div class="title-box">
              <a href="<?php echo $site->url(); ?>" class="site-title"><h1><span class="retopea">Retopea</span><br>
                <?php if($site->title() == "Start"):?>
                    Religious Toleration and Peace
                <?php else: ?>
                    <?php echo $site->title(); ?>
                <?php endif; ?>
              </h1></a>
            </div>
          </div>
        </div>

        <div id="content" role="main">
            <?php echo $this->content; ?>
        </div>
        <footer>
          <div class="logos">
            <img src="<?php echo $this->assetUrl("images/retopea.png");?>">
            <a href="https://kuleuven.be/<?php echo $english;?>"><img src="<?php echo $this->assetUrl("images/kuleuven.PNG");?>"></a>
            <a href="http://libis.be/"><img src="<?php echo $this->assetUrl("images/libis_gray.png");?>"></a>
            <div class="horizon">
              <img src="<?php echo $this->assetUrl("images/2020.png");?>">
            </div>
          </div>

        </footer>
    </body>
</html>
