<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();

$libis = $this->plugin('Libis');
$lang = $libis->getLanguage();
?>

<h1>
    <?php echo implode(", ",$item->value('dcterms:title',array('all' => 'true','lang' => $lang)));?>
</h1>

<?php $this->trigger('view.show.before'); ?>
<div class="item-show">
  <?php if ($embedMedia && $itemMedia): ?>
      <div class="media-embeds">
      <?php foreach ($itemMedia as $media):
          echo $media->render();
      endforeach;
      ?>
      </div>
  <?php endif; ?>

  <?php //echo $this->translator->getLocale();?>
  <div class="metadata">
    <?php echo $item->displayValues(); ?>
    <?php $values = $item->values(); ?>
    <?php //foreach($values as $key=>$value):?>
        <?php //echo $item->value('dcterms:title',array('all' => 'true','lang' => $lang));?>
    <?php //endforeach;?>


    <div class="property">
        <?php $itemSets = $item->itemSets(); ?>
        <?php if (count($itemSets) > 0): ?>
        <h4><?php echo $this->translate('Item sets'); ?></h4>
        <?php foreach ($item->itemSets() as $itemSet): ?>
        <div class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a></div>
        <?php endforeach; ?>
        <?php endif; ?>
    </div>
  </div>

  <?php
  $page = $this->params()->fromQuery('page', 1);
  $property = $this->params()->fromQuery('property');
  $subjectValues = $item->displaySubjectValues($page, 25, $property);
  ?>
  <?php if ($subjectValues): ?>
  <div id="item-linked">
      <h3><?php echo $this->translate('Linked resources'); ?></h3>
      <?php echo $subjectValues; ?>
  </div>
  <?php endif; ?>
</div>
<?php $this->trigger('view.show.after'); ?>
